### ISSUE TITLE
middleman build is realy slow

### ISSUE THREAD

**Issue by ghost** [techpeace/personal-site-template#13]
I just gave middleman a try and used  personal-site-template for the first time. Testing a blog with 2 pages tooks 5m51.632s to build which I found terrible slow.
Can you please point me to some common bottlenecks that could explain this behaviour?

I am running this with ruby 1.9.3p194 in a kvm based virtual machine.

**Comment by techpeace** [comment]
Unfortunately, your pain tolerance is going to be highly dependent upon the speed of your machine, in this instance. The best thing I can recommend would be to simply delete files that you aren't using from the manifest files (`application.js` and `application.scss.css`). You could also try asking the fine folks over at [the Middleman forum](http://forum.middlemanapp.com/).
